version: "3.8"

services:

    lucky-frontend:
        restart: always
        image: kaitoryouga/report_frontend:latest
        expose:
            - 8080
        environment:
            HTTP_PORT: 80
            VIRTUAL_HOST: report.kaito.ninja
            LETSENCRYPT_HOST: report.kaito.ninja
            LETSENCRYPT_EMAIL: "kmactfweb@gmail.com"
        networks:
            service_network:

    lucky-backend:
        restart: always
        image: kaitoryouga/report_backend:latest
        expose:
            - 3001
        environment:
            HTTP_PORT: 3001
            VIRTUAL_HOST: apireport.kaito.ninja
            LETSENCRYPT_HOST: apireport.kaito.ninja
            LETSENCRYPT_EMAIL: "kmactfweb@gmail.com"
        networks:
            service_network:

    tuvan:
        restart: always
        image: kaitoryouga/tuvan:latest
        expose:
            - 9090
        environment:
            HTTP_PORT: 9090
            VIRTUAL_HOST: devf.tech
            LETSENCRYPT_HOST: devf.tech
            LETSENCRYPT_EMAIL: "kmactfweb@gmail.com"
        networks:
            service_network:
        command: /bin/bash
        tty: true

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --interval 5

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        container_name: nginx-proxy
        networks:
            service_network:
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
            - nginx-vhost:/etc/nginx/vhost.d
            - nginx-html:/usr/share/nginx/html

networks:
    service_network:

volumes:
    nginx-certs:
    nginx-vhost:
    nginx-html: