version: "3.8"

services:
  frontend:
    restart: always
    build: 
        context: ./frontend
        dockerfile: Dockerfile.dev
    ports:
    - "81:3000"
    volumes: 
    - ./frontend:/app
  backend:
    restart: always
    build: 
        context: ./backend
        dockerfile: Dockerfile
    ports:
    - "3002:3001"