name: ci

on:
  push:
    branches: master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        run: docker-compose -p report build

      - 
        name: Push image
        run: |
          VERSION=latest
          docker tag report_frontend kaitoryouga/report_frontend:$VERSION
          docker tag report_backend kaitoryouga/report_backend:$VERSION
          docker push kaitoryouga/report_frontend:$VERSION
          docker push kaitoryouga/report_backend:$VERSION